                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

In [1]:
import numpy as np

#### 1. Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [4]:
arr = np.arange(-1.3, 2.5, 64)
arr

TypeError: unsupported operand type(s) for -: 'list' and 'int'

#### 2. Generate an array of length  3n  filled with the cyclic pattern 1, 2, 3.

#### 3. Create an array of the first 10 odd integers.

In [5]:
arr = np.arange(1, 20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 4. Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [8]:
arr = np.zeros([10, 10])
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 5. Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [10]:
arr = np.zeros([8, 8])

arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])