In [4]:
import numpy as np

In [32]:
arr_1d = np.zeros((10))
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
arr_1d + 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [36]:
arr_1d_ones = np.ones(10)
arr_1d_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
arr_1d_ones * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [44]:
# Creating array of any number
x = np.zeros(10)
x = x + 5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Shape of Array
x = np.zeros((3,2,5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [57]:
x.shape

(3, 2, 5)

In [92]:
# Array of custom elements
y = np.array([2,4,6,8,0,5,34,67,87, 22, 33, 12])
z = y.reshape(2, 2,3)
z

array([[[ 2,  4,  6],
        [ 8,  0,  5]],

       [[34, 67, 87],
        [22, 33, 12]]])

In [93]:
z.ndim

3

In [102]:
# Accessing individual elements of array
print(z[1, 0, 1])
print(z[0, 1, 0])

67
8


In [103]:
z.dtype

dtype('int32')

In [106]:
y = y.reshape(4, 3)
y

array([[ 2,  4,  6],
       [ 8,  0,  5],
       [34, 67, 87],
       [22, 33, 12]])

In [111]:
y[0:2]

array([[2, 4, 6],
       [8, 0, 5]])

In [127]:
y[0:4,0]

array([ 2,  8, 34, 22])

In [141]:
y[::,::2]

array([[ 2,  6],
       [ 8,  5],
       [34, 87],
       [22, 12]])

In [118]:
y[::2]

array([[ 2,  4,  6],
       [34, 67, 87]])

In [119]:
y[::3]

array([[ 2,  4,  6],
       [22, 33, 12]])

In [142]:
# Vectorized Operations
p = np.array([1, 5, 7])
q = np.array([2, 4, 6])

In [143]:
p + q

array([ 3,  9, 13])

In [144]:
p - q

array([-1,  1,  1])

In [145]:
p * q

array([ 2, 20, 42])

In [146]:
p / q

array([0.5       , 1.25      , 1.16666667])

In [148]:
1/p

array([1.        , 0.2       , 0.14285714])

In [149]:
p*q**2

array([  4,  80, 252])

In [5]:
x = np.empty((9,9))
x = x + 1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
# Comparison between two matrix
salary = np.array([10, 12, 15, 18, 20, 24, 25])
salary[salary > 15]

array([18, 20, 24, 25])

In [8]:
nums = [10, 20, 56, 78, 90]
np.sin(nums)

array([-0.54402111,  0.91294525, -0.521551  ,  0.51397846,  0.89399666])

In [9]:
nums = [10, 20, 56, 78, 90]
np.sqrt(nums)

array([3.16227766, 4.47213595, 7.48331477, 8.83176087, 9.48683298])

# Vectorization

In [10]:
arr = np.zeros((2, 10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr + 10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [12]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
arr1 = np.ones((2, 10))
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr + arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [2]:
l1 = [1, 2, 4, 5]
l2 = [3, 4, 6, 7]

sum = []
for i,_ in enumerate(l1):
    sum.append(l1[i] + l2[i])
print(sum)

[4, 6, 10, 12]


In [5]:
arr_l1 = np.array(l1)
arr_l2 = np.array(l2)

arr_l1 + arr_l2

array([ 4,  6, 10, 12])

np.where

In [7]:
marks = np.array([75, 39, 50, 80, 90])

In [12]:
x = np.where(marks >= 50, marks, 'fail')
x

array(['75', 'fail', '50', '80', '90'], dtype='<U11')

In [14]:
salary = np.array([25000, 28000, 30000, 32000, 40000])

incremented_salary = np.where(salary >= 30000, salary*1.05, salary*1.3)

%time incremented_salary

CPU times: total: 0 ns
Wall time: 0 ns


array([32500., 36400., 31500., 33600., 42000.])

In [16]:
arr = np.arange(1, 101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [18]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [21]:
arr = np.array([3, 4, 6, 7, 8])
arr.mean()

5.6

In [22]:
arr.cumsum()

array([ 3,  7, 13, 20, 28])

In [23]:
arr.cumprod()

array([   3,   12,   72,  504, 4032])

# Methods for boolean arrays

In [32]:
gender = np.array(['Male','Female','Male','Female','Male'])

arr = gender == 'Male'
print(arr)

[ True False  True False  True]


In [27]:
arr.sum()

3

In [30]:
gender = np.array(['Male','Female','Male','Female','Male'])

arr = gender == 'Female'
print(arr)

[False  True False  True False]


In [31]:
arr.sum()

2

In [33]:
arr

array([ True, False,  True, False,  True])

In [34]:
arr.any()

True

In [35]:
arr.all()

False

In [43]:
arr = np.array([2, 4, 11, 20, 16])

In [44]:
x = (arr % 2 == 0)
x

array([ True,  True, False,  True,  True])

In [45]:
x.all()

False

# Universal Quantifier

In [50]:
arr[2] = 10
arr

array([ 2,  4, 10, 16, 20])

In [49]:
arr.sort()
arr

array([ 2,  4, 10, 16, 20])

In [52]:
arr[::-1]

array([20, 16, 10,  4,  2])

In [53]:
arr

array([ 2,  4, 10, 16, 20])

In [57]:
arr = np.array([1, 2, 4, 3, 1, 2, 3, 5, 6])

In [58]:
u = np.unique(arr)
u

array([1, 2, 3, 4, 5, 6])

# Save array

In [59]:
np.save('data', u)

In [60]:
# Load array
content = np.load('data.npy')

content

array([1, 2, 3, 4, 5, 6])

In [62]:
# Saving multiple arrays
students = np.array(['Ali', 'Asad', 'Ahmed', 'Amir'])
marks = np.array([55, 60, 68, 56, 69])

In [63]:
np.savez('result', students=students, marks=marks)

In [68]:
results = np.load('result.npz')

print(results['students'])
print()
print(results['marks'])

['Ali' 'Asad' 'Ahmed' 'Amir']

[55 60 68 56 69]


In [69]:
arr = np.arange(1,17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
arr.diagonal()

array([ 1,  6, 11, 16])

In [2]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# C order
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# F Fortran order
arr.ravel('F')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])

In [13]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [14]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
arr = np.random.randn(6,2)
arr

array([[ 1.29656102,  0.03305509],
       [-0.13816146, -0.2064384 ],
       [ 0.68533177, -0.18265236],
       [ 0.92034404,  1.06454019],
       [ 0.16082445, -0.47585459],
       [-0.33127229,  1.03205223]])

In [28]:
first, second, third = np.split(arr, [1, 3])

In [23]:
first

array([[1.29656102, 0.03305509]])

In [24]:
second

array([[-0.13816146, -0.2064384 ],
       [ 0.68533177, -0.18265236]])

In [25]:
third

array([[ 0.92034404,  1.06454019],
       [ 0.16082445, -0.47585459],
       [-0.33127229,  1.03205223]])

In [32]:
# Stacking helper r_ and c_
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
arr1 = arr.reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
arr2 = np.random.randn(3, 2)
arr2

array([[ 0.57331479,  0.99790232],
       [-0.9077897 ,  0.38068122],
       [ 0.25712748, -0.34736013]])

In [37]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.57331479,  0.99790232],
       [-0.9077897 ,  0.38068122],
       [ 0.25712748, -0.34736013]])

In [40]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.57331479,  0.99790232,  3.        ],
       [-0.9077897 ,  0.38068122,  4.        ],
       [ 0.25712748, -0.34736013,  5.        ]])

In [42]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [38]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  0.57331479,  0.99790232],
       [ 2.        ,  3.        , -0.9077897 ,  0.38068122],
       [ 4.        ,  5.        ,  0.25712748, -0.34736013]])

Repeating Elements: tile and repeat

In [44]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [47]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [50]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [52]:
arr = np.random.randn(2,2)
arr

array([[-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394]])

In [55]:
arr.repeat(2, axis=0)

array([[-0.84462772, -1.54956989],
       [-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394],
       [ 0.39748791,  0.12287394]])

In [56]:
arr.repeat([2, 3], axis=0)

array([[-0.84462772, -1.54956989],
       [-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394],
       [ 0.39748791,  0.12287394],
       [ 0.39748791,  0.12287394]])

In [57]:
arr.repeat([2, 3], axis=1)

array([[-0.84462772, -0.84462772, -1.54956989, -1.54956989, -1.54956989],
       [ 0.39748791,  0.39748791,  0.12287394,  0.12287394,  0.12287394]])

Tile

In [58]:
arr

array([[-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394]])

In [59]:
np.tile(arr, 2)

array([[-0.84462772, -1.54956989, -0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394,  0.39748791,  0.12287394]])

In [68]:
np.tile(arr, (2, 1))

array([[-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394],
       [-0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394]])

In [69]:
np.tile(arr, (3, 2))

array([[-0.84462772, -1.54956989, -0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394,  0.39748791,  0.12287394],
       [-0.84462772, -1.54956989, -0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394,  0.39748791,  0.12287394],
       [-0.84462772, -1.54956989, -0.84462772, -1.54956989],
       [ 0.39748791,  0.12287394,  0.39748791,  0.12287394]])

Fancy Indexing Equivalents; take and put

In [72]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [73]:
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [74]:
arr.take(inds)

array([700, 100, 200, 600])

In [77]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [79]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [80]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[ 0.11478939, -0.89687143,  0.48095008,  1.65265168],
       [-0.51397557,  0.29121041, -1.0373679 ,  0.43369623]])

In [81]:
arr.take(inds, axis=1)

array([[ 0.48095008,  0.11478939,  0.48095008, -0.89687143],
       [-1.0373679 , -0.51397557, -1.0373679 ,  0.29121041]])

A.3 Broadcasting

In [82]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [83]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [84]:
arr = np.random.randn(4, 3)
arr

array([[-1.00053483,  1.50681594,  0.58481215],
       [ 0.2293943 ,  0.70807853,  0.39390278],
       [-0.35925025, -0.6412654 , -0.22409774],
       [-1.68757441, -0.65964556,  0.45972157]])

In [89]:
arr.mean(0)

array([-0.7044913 ,  0.22849588,  0.30358469])

In [90]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.29604353,  1.27832006,  0.28122746],
       [ 0.9338856 ,  0.47958265,  0.09031809],
       [ 0.34524105, -0.86976128, -0.52768243],
       [-0.98308311, -0.88814144,  0.15613688]])

In [91]:
demeaned.mean(0)

array([0.00000000e+00, 5.55111512e-17, 1.38777878e-17])

In [92]:
arr

array([[-1.00053483,  1.50681594,  0.58481215],
       [ 0.2293943 ,  0.70807853,  0.39390278],
       [-0.35925025, -0.6412654 , -0.22409774],
       [-1.68757441, -0.65964556,  0.45972157]])

In [98]:
row_mean = arr.mean(1)

In [101]:
print(row_mean)
print(row_mean.shape)

[ 0.36369775  0.44379187 -0.40820446 -0.62916613]
(4,)


In [102]:
row_mean.reshape(4,1)

array([[ 0.36369775],
       [ 0.44379187],
       [-0.40820446],
       [-0.62916613]])

A.4 Advanced ufunc Usage

In [104]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.add.reduce(arr)

45

In [106]:
arr.sum()

45

In [109]:
np.random.seed(12346)

In [110]:
arr = np.random.randn(5,5)
arr

array([[-8.99822478e-02,  7.59372617e-01,  7.48336101e-01,
        -9.81497953e-01,  3.65775545e-01],
       [-3.15442628e-01, -8.66135605e-01,  2.78568155e-02,
        -4.55597723e-01, -1.60189223e+00],
       [ 2.48256116e-01, -3.21536673e-01, -8.48730755e-01,
         4.60468309e-04, -5.46459347e-01],
       [ 2.53915229e-01,  1.93684246e+00, -7.99504902e-01,
        -5.69159281e-01,  4.89244731e-02],
       [-6.49092950e-01, -4.79535727e-01, -9.53521432e-01,
         1.42253882e+00,  1.75403128e-01]])

In [111]:
arr[:, :-1] < arr[:,1:]

array([[ True, False, False,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

# Exam Key: nm23p8

In [114]:
a = np.array([0,1])
b = np.array([0,2])
np.column_stack((a,b))

array([[0, 0],
       [1, 2]])

In [115]:
arr = [0.3490, -1.4545, 1.204, -9.7152, 11.43, -0.8439]
arr.sort()
print(arr)

[-9.7152, -1.4545, -0.8439, 0.349, 1.204, 11.43]


In [116]:
arr = np.array([0, 1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [117]:
print(np.arange(9, -1, -1))

[9 8 7 6 5 4 3 2 1 0]


In [120]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(np.concatenate((b,a), axis=0))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [121]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [123]:
arr = np.arange(10)
arr_slice = arr[8:5]
arr_slice[:] = 69
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.concatenate([a, b], axis=0))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [125]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.vstack([a, b]))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [127]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.r_[a, b])


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [129]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.hsplit(a,3)

[array([[10],
        [40],
        [70]]),
 array([[20],
        [50],
        [80]]),
 array([[30],
        [60],
        [90]])]

In [130]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(np.concatenate((a,b), axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [131]:
a = np.array([[0,1,2,45],[3,4,5, 7],[6,7,8,8]])
b = np.array([[0,2,4, 47],[6,8,10,9],[12,14,16,7]])
print(np.dstack((a,b)))

[[[ 0  0]
  [ 1  2]
  [ 2  4]
  [45 47]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]
  [ 7  9]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]
  [ 8  7]]]


In [ ]:
np.reshape()

In [132]:
Numpy.array(list)

NameError: name 'Numpy' is not defined

In [133]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2==1]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [139]:
np.max(arr)

8

In [140]:
np.arr(max)

AttributeError: module 'numpy' has no attribute 'arr'

In [141]:
arr.max()

8

In [ ]:
arr.type()

In [ ]:
arr = np.array([67.98, -10.25, -22.06, 0.5])