In [ ]:
import numpy as np

: 

In [8]:
# Create a NumPy ndarray Object

arr = np.array([1, 2, 3, 4, 5]) # 
print(arr)
print(type(arr))

arr1 = np.array((1, 2, 3, 4, 5)) # 
print(arr1)
print(type(arr1))

lst = ['a', 'b', 'c', 'd', 'e']
arr2 = np.array(lst)
print(arr2)
print(type(arr2))

tpl = ('a', 'b', 'c', 'd', 'e')
tpl = np.array(tpl)
print(tpl)
print(type(tpl))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
['a' 'b' 'c' 'd' 'e']
<class 'numpy.ndarray'>
['a' 'b' 'c' 'd' 'e']
<class 'numpy.ndarray'>


In [26]:
# 0D Arrays
arr = np.array(42)
print(arr)

# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2D Arrays
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
arr.shape

# 3D Arrays
arr = np.array([
    [[1,2,3], [4,5,6], [4,5,6]], 
    [[7,8,9], [1,2,3], [4,5,6]], 
    [[7,8,9], [1,2,3], [4,5,6]]])
print(arr)
print(arr.shape)
print(arr.ndim)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]]]
(3, 3, 3)
3


In [2]:
# Check Number of Dimensions?

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimentions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimentions : 5


## NumPy Array Indexing

In [7]:
# Access Array Elements
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [8]:
# Access Array Elements
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [10]:
# Get third and fourth elements from the following array and add them
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


## NumPy Array Slicing

## Data Types in NumPy

* i - integer
* b - boolean
* u - unsigned interger
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - Object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type (void)

#### Checking the Data Type of an Array

In [11]:
arr =  np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [12]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
