# Chapter 5
### Getting Started with pandas

In [1]:
import pandas as pd
import numpy as np

# Series

In [227]:
obj = pd.Series([4, 7, -5, 3])

In [228]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [161]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [162]:
obj2 = pd.Series([23, 44, 54, 78, 56], index=['a', 'b', 'c', 'd', 'e'])

In [163]:
obj2

a    23
b    44
c    54
d    78
e    56
dtype: int64

In [164]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

Using indexes to access data

In [165]:
obj2['a']

23

In [166]:
obj2['e'] = 420

In [167]:
obj2[['a', 'e', 'c']]

a     23
e    420
c     54
dtype: int64

In [168]:
obj2[obj2 > 50]

c     54
d     78
e    420
dtype: int64

In [169]:
print(obj2)
print()

print(obj2 * 2)

a     23
b     44
c     54
d     78
e    420
dtype: int64

a     46
b     88
c    108
d    156
e    840
dtype: int64


In [170]:
'b' in obj2

True

Creating seris from dictionary

In [171]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [172]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [173]:
# Checking for null values
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [174]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [175]:
# Addind two series
obj3, obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64)

In [176]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [177]:
data = {
    'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year'  : [2000, 2001, 2002, 2001, 2002, 2003],
    'pop'   : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2] 
}

frame = pd.DataFrame(data, index=['one', 'two', 'three', 'four', 'five', 'six'])

In [178]:
# Show first five rows
frame.head()

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9

In [179]:
frame.head(3)

state  year  pop
one    Ohio  2000  1.5
two    Ohio  2001  1.7
three  Ohio  2002  3.6

In [180]:
frame.head(-2)

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4

In [181]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index= ['one','two','three','four','five','six'])

In [182]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [183]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [184]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [185]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [186]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [187]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [188]:
frame2['debt'] = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

### Adding / deleting a new column

In [189]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5     0     True
two    2001    Ohio  1.7     1     True
three  2002    Ohio  3.6     2     True
four   2001  Nevada  2.4     3    False
five   2002  Nevada  2.9     4    False
six    2003  Nevada  3.2     5    False

In [190]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [191]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [192]:
frame3 = frame2.T

In [193]:
frame3

one   two three    four    five     six
year   2000  2001  2002    2001    2002    2003
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9     3.2
debt      0     1     2       3       4       5

In [194]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [195]:
frame2.values

array([[2000, 'Ohio', 1.5, 0],
       [2001, 'Ohio', 1.7, 1],
       [2002, 'Ohio', 3.6, 2],
       [2001, 'Nevada', 2.4, 3],
       [2002, 'Nevada', 2.9, 4],
       [2003, 'Nevada', 3.2, 5]], dtype=object)

Indexing, selection and filtering

In [196]:
obj = pd.Series(np.arange(1,11.), index=['a','b','c','d','e','f','g','h','i','j'])
obj

a     1.0
b     2.0
c     3.0
d     4.0
e     5.0
f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
dtype: float64

In [197]:
obj[['c', 'e', 'i']]

c    3.0
e    5.0
i    9.0
dtype: float64

In [198]:
obj[obj > 5]

f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
dtype: float64

In [199]:
new_obj = obj.drop('c')
new_obj

a     1.0
b     2.0
d     4.0
e     5.0
f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
dtype: float64

In [200]:
new_obj

a     1.0
b     2.0
d     4.0
e     5.0
f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
dtype: float64

In [201]:
data = np.arange(16).reshape(4,4)
data
data_frame = pd.DataFrame(data, columns=['one','two','three','four'], index=['Ohio','Colorado','Utah','New York'])

In [202]:
data_frame

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Axis Parameter

In [203]:
data_frame.drop('two', axis=1)


one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [204]:
data_frame.drop(['two','three'], axis='columns')

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [205]:
data_frame.drop('Utah', axis=0)

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [206]:
obj

a     1.0
b     2.0
c     3.0
d     4.0
e     5.0
f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
dtype: float64

In [207]:
obj[1]

2.0

In [208]:
obj[2:6]

c    3.0
d    4.0
e    5.0
f    6.0
dtype: float64

In [209]:
obj[['b','a','d']]

b    2.0
a    1.0
d    4.0
dtype: float64

In [210]:
obj[[1,0,3]]

b    2.0
a    1.0
d    4.0
dtype: float64

In [211]:
data_frame

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [212]:
print(data_frame.loc['Colorado']) # location
print()

print(data_frame.loc['Colorado', ['two','three']]) # location + columns

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

two      5
three    6
Name: Colorado, dtype: int32


In [213]:
print(data_frame.iloc[1])
print()

print(data_frame.iloc[1, [1,2]])


one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

two      5
three    6
Name: Colorado, dtype: int32


In [214]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}
}

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [215]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [216]:
print(pop)
print()

pd.DataFrame(pop, index=[2001, 2002, 2003])


{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}



Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [217]:
pdata = {
    'Ohio'  :frame3['Ohio'][:-1],
    'Nevada':frame3['Nevada'][:2] 
}

print(pdata)
pd.DataFrame(pdata)

{'Ohio': 2001    1.7
2002    3.6
Name: Ohio, dtype: float64, 'Nevada': 2001    2.4
2002    2.9
Name: Nevada, dtype: float64}


Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [218]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [219]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [220]:
frame2.values

array([[2000, 'Ohio', 1.5, 0],
       [2001, 'Ohio', 1.7, 1],
       [2002, 'Ohio', 3.6, 2],
       [2001, 'Nevada', 2.4, 3],
       [2002, 'Nevada', 2.9, 4],
       [2003, 'Nevada', 3.2, 5]], dtype=object)

# Index Objects

In [221]:
obj =  pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index


In [222]:
index

Index(['a', 'b', 'c'], dtype='object')

In [223]:
index[1:]

Index(['b', 'c'], dtype='object')

In [224]:
# Index objects are immutable and thus can't be modified by ther user:
index['c'] = 3

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [ ]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.index

False

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [ ]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### Table 5-2. Some Index methods and properties

In [ ]:
# append()
idx1 = pd.Index(['Jan', 'Feb', 'Mar', 'Apr'])
print(idx1)

idx2 = pd.Index(['May', 'Jun', 'Jul', 'Aug'])
idx3 = pd.Index(['Sep', 'Oct', 'Nov', 'Dec'])

idx1.append([idx2, idx3])

Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')


Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
       'Nov', 'Dec'],
      dtype='object')

In [ ]:
# difference() ex1
idx = pd.Index([17, 69, 33, 15, 19, 74, 10, 5])
print(idx)

idx.difference([69, 33, 15, 74, 19])

Int64Index([17, 69, 33, 15, 19, 74, 10, 5], dtype='int64')


Int64Index([5, 10, 17], dtype='int64')

In [ ]:
# difference() ex2
idx1 = pd.Index(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

idx2 = pd.Index(['May','Jun','Jul','Aug'])

print(idx1, '\n', idx2)

idx1.difference(idx2)

Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
       'Nov', 'Dec'],
      dtype='object') 
 Index(['May', 'Jun', 'Jul', 'Aug'], dtype='object')


Index(['Apr', 'Dec', 'Feb', 'Jan', 'Mar', 'Nov', 'Oct', 'Sep'], dtype='object')

In [ ]:
# intersection() ex1 (common elements)
idx1 = pd.Index(['Labrador','Beagle','Mastif','Lhasa','Husky','Beagle'])
idx2 = pd.Index(['Labrador','Greate_Dane','PUg','German_sepherd','Husky','Pitbull'])

print(idx1, '\n', idx2)

idx2.intersection(idx1)

Index(['Labrador', 'Beagle', 'Mastif', 'Lhasa', 'Husky', 'Beagle'], dtype='object') 
 Index(['Labrador', 'Greate_Dane', 'PUg', 'German_sepherd', 'Husky', 'Pitbull'], dtype='object')


Index(['Labrador', 'Husky'], dtype='object')

In [ ]:
idx1 = pd.Index(['2015-10-31','2015-12-02',None,'2016-01-03','2016-02-08','2017-05-05','2014-02-11'])
idx2 = pd.Index(['2015-10-31','2015-10-02','2018-01-03','2016-02-08','2017-06-05','2014-07-11',None])

print(idx1, '\n\n', idx2)

idx1.intersection(idx2)

Index(['2015-10-31', '2015-12-02',         None, '2016-01-03', '2016-02-08',
       '2017-05-05', '2014-02-11'],
      dtype='object') 

 Index(['2015-10-31', '2015-10-02', '2018-01-03', '2016-02-08', '2017-06-05',
       '2014-07-11',         None],
      dtype='object')


Index(['2015-10-31', None, '2016-02-08'], dtype='object')

In [ ]:
# isin() ex1
idx = pd.Index(['Labrador','Beagle','Mastif','Lhasa','Husky','Beagle'])

idx.isin(['Labrador', 'Lhasa'])

array([ True, False, False,  True, False, False])

In [ ]:
# isin() ex2
midx = pd.MultiIndex.from_arrays([
    ['Mon','Tue','Wed','The'],
    [10, 20, 30, 40]
], names=('Days', 'Target'))

midx

MultiIndex([('Mon', 10),
            ('Tue', 20),
            ('Wed', 30),
            ('The', 40)],
           names=['Days', 'Target'])

In [ ]:
midx.isin(['Tue','Wed','Fri','Sat'], level='Days')

array([False,  True,  True, False])

In [ ]:
midx.isin([20, 40, 60, 80], level='Target')

array([False,  True, False,  True])

# 5.2 Essential Functionality

## Reindexing

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj.reindex(['a','b','c','d','e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method='ffill')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [229]:
frame =pd.DataFrame(np.arange(9).reshape(3,3), index=['a','c','d'], columns=['Ohio', 'Texas','California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [232]:
states = ['Texas','Utah','California']

In [233]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [236]:
frame.loc[['a','b','c','d'], states]

KeyError: "['b'] not in index"

# Chapter 6
### Data Loading, Storage, and Files Formats

In [ ]:
!edit example/ex2.csv
a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [8]:
df = pd.read_csv('example/ex1.csv')
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
pd.read_table('example/ex1.csv', sep=',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
pd.read_csv('examples/ex2.csv', header=None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [12]:
pd.read_csv('examples/ex2.csv', names=['a','b','c','d','message'])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
names=['a','b','c','d','message']
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [15]:
parsed = pd.read_csv('examples/csv_mindex.csv', index_col=['key1','key2'])

In [16]:
parsed

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [1]:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [3]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [5]:
pd.read_csv('examples/ex4.csv', skiprows=[0,2,3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
result = pd.read_csv('examples/ex5.csv')
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [9]:
pd.isnull(result)

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [10]:
result = pd.read_csv('examples/ex5.csv', na_values=['NULL'])
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [11]:
sentinals = {'message': ['foo', 'NA'], 'something': ['two']}

In [12]:
pd.read_csv('examples/ex5.csv', na_values=sentinals)

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

### Reading Text Files in Pieces

In [13]:
pd.options.display.max_rows = 10  # pandas display settings 10 rows

In [15]:
result = pd.read_csv('examples/ex6.csv')
result

one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [19]:
# Display only 5 rows 

result = pd.read_csv('examples/ex6.csv', nrows=5)   
result

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [20]:
# Specify a chunksize as a number of rows

chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

In [25]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

d:\Program Files\Python37-32\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
tot[:10]

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

### Writing Data to Text Format

In [26]:
data = pd.read_csv('examples/ex5.csv')
data

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [27]:
data.to_csv('example/out.csv')

In [28]:
# Other delimiters can be used
import sys

data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo


In [29]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo


In [30]:
# row and column labels can be disable
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo


In [35]:
#  only a subset of the columns, and in an order of your choosing:
data.to_csv(sys.stdout, index=False, columns=['a','b','c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0


### Series also has a to_csv method:

In [44]:
dates = pd.date_range('1/1/2023', periods=7)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07'],
              dtype='datetime64[ns]', freq='D')

In [45]:
ts = pd.Series(np.arange(7), index=dates)
ts

2023-01-01    0
2023-01-02    1
2023-01-03    2
2023-01-04    3
2023-01-05    4
2023-01-06    5
2023-01-07    6
Freq: D, dtype: int32

In [46]:
ts.to_csv('example/tseries.csv')

### Working with Delimited Formats

In [48]:
import csv

f = open('examples/ex7.csv')
reader = csv.reader(f)

for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


In [54]:
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))

print(lines)

header, values = lines[0], lines[1:]
print(header, values)

data_dict = {h: v for h, v in zip(header, zip(*values))}

data_dict

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]
['a', 'b', 'c'] [['1', '2', '3'], ['1', '2', '3']]


{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [62]:
f = open('examples/ex7.csv')
reader = csv.reader(f)


class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

reader = csv.reader(f, dialect=my_dialect)

In [61]:
f = open('examples/ex7.csv')
reader = csv.reader(f)

reader = csv.reader(f, delimiter='|')

In [64]:
with open('example/mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one','two','three'))
    writer.writerow(('1','2','3'))
    writer.writerow(('4','5','6'))
    writer.writerow(('7','8','9'))

### JSON Data

In [14]:
import json

obj = """
{
    "name":"Wes",
    "places_lived": ["United States", "Spain", "Germany"],
    "pet": null,
    "siblings": [{"name":"Scott", "age":30, "pets":["Zeus","Zuko"]},
                {"name":"Katie", "age":38, "pets":["Sixes", "Stache", "Cisco"]}]
}
"""

result = json.loads(obj)
result

# JSON object convert to python object

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [15]:
# Python object convert to JSON Object

asjson = json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [21]:
# Convert a JSON object or list of objects to a DataFrame

siblings = pd.DataFrame(result['siblings'], columns=['name','age'])
siblings

name  age
0  Scott   30
1  Katie   38

In [19]:
data = pd.read_json('examples/example.json')
data

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [22]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}


In [23]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]


### 6.2 Binary Data Formats

In [25]:
# Serialization (Pickle Method)
frame = pd.read_csv('examples/ex1.csv')
frame

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [28]:
frame.to_pickle('example/frame_pickle')

In [29]:
# read built-in pickle file
pd.read_pickle('example/frame_pickle')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### 

### Using HDF5 Format (Hierarchical Data Format)

In [30]:
frame = pd.DataFrame({'a': np.random.randn(100)})

In [31]:
frame

a
0  -0.266792
1   0.410853
2   0.830397
3  -0.412451
4  -0.716409
..       ...
95  0.488026
96 -0.094636
97 -0.067309
98 -1.219283
99 -0.472464

[100 rows x 1 columns]

In [39]:
store = pd.HDFStore('example/mydata.h5')

In [40]:
store['obj1'] = frame

In [41]:
store['obj1_col'] = frame['a']

In [42]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: example/mydata.h5

In [43]:
store['obj1']

a
0  -0.266792
1   0.410853
2   0.830397
3  -0.412451
4  -0.716409
..       ...
95  0.488026
96 -0.094636
97 -0.067309
98 -1.219283
99 -0.472464

[100 rows x 1 columns]

In [44]:
store.put('obj2', frame, format='table')

In [46]:
store.select('obj2', where=['index >= 10 and index <= 15'])

a
10 -2.648577
11  0.253685
12 -0.498609
13  0.637296
14 -0.924490
15 -1.501489

In [47]:
store.close()

In [49]:
frame.to_hdf('example/mydata.h5', 'obj3', format='table')

In [50]:
pd.read_hdf('example/mydata.h5', 'obj3', where=['index < 5'])

a
0 -0.266792
1  0.410853
2  0.830397
3 -0.412451
4 -0.716409

### Reading Microsoft Excel Files

In [52]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')

In [53]:
pd.read_excel(xlsx, 'Sheet1')

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [54]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1')
frame

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [55]:
writer = pd.ExcelWriter('example/ex2.xlsx')

In [56]:
frame.to_excel(writer, 'Sheet1')

In [57]:
writer.save()

In [58]:
# in-Short
frame.to_excel('example/ex2_v1.xlsx')

### 6.3 Interacting with Web APIs

In [59]:
import requests

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [60]:
data = resp.json()
data[0]['title']

'Depricate DataFrame.resample axis parameter'

In [62]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])

In [63]:
issues

number                                              title  \
0    51901        Depricate DataFrame.resample axis parameter   
1    51900         ENH: strip debug symbols from macOS wheels   
2    51899                         assert_frame_equal for set   
3    51898                                Upstream roperator?   
4    51896  BUG: disallow resample with non-Tick on Timede...   
5    51895  BUG: Fix getitem dtype preservation with multi...   
6    51894                     CI/STYLE: Add auto-fix to ruff   
7    51892  BUG: Unexpected KeyError message when using .l...   
8    51891                        BUG: agg uint8 works wrong.   
9    51885  PERF: Casting as type `string[pyarrow]` is sig...   
10   51883  BUG: pd.DataFrame.from_dict with a numpy maske...   
11   51882  BUG: Incorrect parsing of ISO 8601 durations s...   
12   51881   DOC update DataFrame.to_csv write modes (#51839)   
13   51880  Semantics between `Series.apply` and `Series.a...   
14   51878  Require Functionality for Handling Foreign Arg...   
15   51876  BUG:  "TypeError: Cannot interpret 'string[pya...   
16   51875  BUG: pandas is using absolute `from pandas._li...   
17   51874                       WIP/API: Make Day not a Tick   
18   51873  PERF: Improve performance of MultiIndex._verif...   
19   51872  BUG: pd.DataFrame.from_dict with a numpy maske...   
20   51871             ERR: Check that dtype_backend is valid   
21   51868          DOC: backslash removed for read_clipboard   
22   51867                             TYP: fix NDFrame.align   
23   51866  QST: InvalidIndexError using at for multiple a...   
24   51863                        TYP: NDFrame.align is wrong   
25   51862  QST: TypeError: read_excel() got an unexpected...   
26   51861  ENH: More helpful error messages for merges wi...   
27   51860    DOC: Change color of sample plots for dark mode   
28   51858  BUG: Get sizeof fails for pandas series or dat...   
29   51856  DEPR: NDFrame.align broadcast_axis, fill_axis ...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
2                                                  []  open  
3   [{'id': 2187005593, 'node_id': 'MDU6TGFiZWwyMT...  open  
4                                                  []  open  
5                                                  []  open  
6                                                  []  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
10                                                 []  open  
11  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
12  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
13  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
14  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4...  open  
18  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...  open  
21  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
22  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
23  [{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...  open  
26  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
27  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### 6.4 Interacting with Databases

In [64]:
import sqlite3

In [65]:
query = "CREATE TABLE test (a VARCHAR(20), b VARCHAR(20), c REAL, d INTEGER);"

In [67]:
con = sqlite3.connect('example/mydata.splite')

In [68]:
con.execute(query)

In [69]:
con.commit()

In [70]:
# insert a few rows of data:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]

stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [72]:
con.executemany(stmt, data)

In [73]:
con.commit()

In [74]:
cursor = con.execute('select * from test')

In [75]:
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [76]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

# Chapter 7
### Data Cleaning and Preparation